// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYmwZls681a0FIi_95Aaj7spiwLBNpUfI',
    appId: '1:1016889261274:web:adb6e5cccf1d26e5e779e3',
    messagingSenderId: '1016889261274',
    projectId: 'attendanceapp-74ff3',
    authDomain: 'attendanceapp-74ff3.firebaseapp.com',
    storageBucket: 'attendanceapp-74ff3.firebasestorage.app',
    measurementId: 'G-EEJQ54CS0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVhusAYm_wEPm9cfXIktY67neUbz50agM',
    appId: '1:1016889261274:android:9790488165af9ca9e779e3',
    messagingSenderId: '1016889261274',
    projectId: 'attendanceapp-74ff3',
    storageBucket: 'attendanceapp-74ff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuv2z-leuVULTuH0SfDHejPUzMIMNB0o4',
    appId: '1:1016889261274:ios:737903558825af83e779e3',
    messagingSenderId: '1016889261274',
    projectId: 'attendanceapp-74ff3',
    storageBucket: 'attendanceapp-74ff3.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuv2z-leuVULTuH0SfDHejPUzMIMNB0o4',
    appId: '1:1016889261274:ios:737903558825af83e779e3',
    messagingSenderId: '1016889261274',
    projectId: 'attendanceapp-74ff3',
    storageBucket: 'attendanceapp-74ff3.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYmwZls681a0FIi_95Aaj7spiwLBNpUfI',
    appId: '1:1016889261274:web:840d74a5c1cd7034e779e3',
    messagingSenderId: '1016889261274',
    projectId: 'attendanceapp-74ff3',
    authDomain: 'attendanceapp-74ff3.firebaseapp.com',
    storageBucket: 'attendanceapp-74ff3.firebasestorage.app',
    measurementId: 'G-BMVKKRR9CN',
  );
}
